### ISSUE TITLE
Error on write when assigning inside lambda

### ISSUE THREAD

**Issue by bgr** [klen/python-mode#554]
This code `lambda: x = 1` will trigger the following error on write:
```
Error detected while processing function pymode#buffer_post_write..pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python-mode/pymode/lint.py", line 71, in code_check
    env.run('g:PymodeLocList.current().extend', [e._info for e in errors])
  File ".../pymode/environment.py", line 186, in run
    self.prepare_value(a) for a in args
vim.error: Vim(call):E121: Undefined variable: null
Error detected while processing function pymode#buffer_post_write:
line   10:
E171: Missing :endif
```

**Comment by dset0x** [comment]
@bgr This should be fixed by this: https://github.com/klen/python-mode/issues/452#issuecomment-60401410

**Comment by klen** [comment]
Thank you for the feedback.
