### ISSUE TITLE
Open file error

### ISSUE THREAD

**Issue by Chunlei-Li** [klen/python-mode#646]
Hi,

I am fresh to python-mode with vim. I encountered errors when I try to open/create a python file.
I tried the command "vim -u /Users/ChunleiLi/.vim/bundle/python-mode/debug.vim", and everything is fine. I tried the command ": Pymodetroubleshooting" and got no warning message. 

I am using Mac OS X EI Capitan and my python version is Python 2.7.11 :: Anaconda 2.4.1 (x86_64)
I have searched for the solution for a while, but was not able to figure out the solution. 

Below are the error messages (which seem to have something to with lint.vim) and the trouble shooting messages. 

********************************************************************************************************************
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"Dropbox/Academic/UiS/DataScience/Ex1.py" 26L, 1111C
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ChunleiLi/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ChunleiLi/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in <module>
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/ChunleiLi/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in <module>
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/anaconda/lib/python2.7/io.py", line 51, in <module>
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/anaconda/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Referenced from: /anaconda/lib/python2.7/lib-dynload/_io.so
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Expected in: dynamic lookup
Error detected while processing /Users/ChunleiLi/.vim/bundle/python-mode/autoload/pymode/lint.vim:

**********************************************************************************
Pymode diagnostic
===================
VIM:704, OS: Darwin, multi_byte:1, pymode: 0.8.1, pymode-python: python

+python: 1
+python3: 0

VIM python paths:
-----------------
/Users/ChunleiLi/.vim/bundle/python-mode/pymode/libs2
/Users/ChunleiLi/.vim/bundle/python-mode/pymode/libs
/Users/ChunleiLi/.vim/bundle/python-mode
/anaconda/lib/python27.zip
/anaconda/lib/python2.7
/anaconda/lib/python2.7/plat-darwin
/anaconda/lib/python2.7/plat-mac
/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/anaconda/lib/python2.7/lib-tk
/anaconda/lib/python2.7/lib-old
/anaconda/lib/python2.7/lib-dynload
/anaconda/lib/python2.7/site-packages
/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg
/anaconda/lib/python2.7/site-packages/aeosa
/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg
_vim_path_

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 0
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 0
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 0
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''

**Comment by Chunlei-Li** [comment]
This problem has been solved in 
https://github.com/klen/python-mode/issues/634#issuecomment-165233451
