### ISSUE TITLE
'module' object has no attribute 'RedefinedInListComp'

### ISSUE THREAD

**Issue by noscripter** [klen/python-mode#655]
When opening a *.py file, I got this error:

```log
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 24, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pyflakes import Linter
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pyflakes.py", line 10, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    checker.messages.RedefinedInListComp.message = "W0621 list comprehension redefines %r from line %r"
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: 'module' object has no attribute 'RedefinedInListComp'
```

output of running `vim -u ~/.vim/bundle/python-mode/debug.vim`:

```
Pymode diagnostic
===================
VIM:704, OS: Darwin, multi_byte:1, pymode: 0.8.1, pymode-python: python


+python: 1
+python3: 0

VIM python paths:
-----------------
/Users/leo/.vim/bundle/python-mode
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/List-1.3.0-py2.7.egg
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/supervisor-3.1.3-py2.7.eg
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/meld3-1.0.2-py2.7.egg
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cachebrowser-0.1.0-py2.7.
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/curtsies-0.1.19-py2.7.egg
/Library/Python/2.7/site-packages
/Library/Python/2.7/site-packages/closure_linter-2.3.13-py2.7.egg
/Library/Python/2.7/site-packages/python_gflags-2.0-py2.7.egg
/Library/Python/2.7/site-packages/cssutils-1.0-py2.7.egg
/Library/Python/2.7/site-packages/distribute-0.7.3-py2.7.egg
/Users/leo/projects/assets/mitmproxy
/Users/leo/projects/assets/mitmproxy/pathod
/Users/leo/projects/assets/mitmproxy/netlib
/Library/Python/2.7/site-packages/setuptools-15.2-py2.7.egg
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0
_vim_path_

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```

**Comment by noscripter** [comment]
And reopen the same *.py file when start vim using `vim -u ~/.vim/bundle/python-mode/debug.vim`, the error is:

```
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: No module named pylama.lint.extensions
```

**Comment by noscripter** [comment]
I believe this problem was caused by lack of pylama, use pip to install fix this issue:`sudo pip install pylama`.

**Comment by noscripter** [comment]
I'm afraid this issue still exist in my situation, I got this error instead:

```
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 24, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pyflakes import Linter
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/leo/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pyflakes.py", line 10, in <module>
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    checker.messages.RedefinedInListComp.message = "W0621 list comprehension redefines %r from line %r"
Error detected while processing /Users/leo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: 'module' object has no attribute 'RedefinedInListComp'
```

**Comment by noscripter** [comment]
Ok, I find this issue was caused by the deprecated plugins:

```
  Plugin 'mitechie/pyflakes-pathogen' " deprecated
  Plugin 'kevinw/pyflakes-vim' " deprecated
  Plugin 'pyflakes.vim' " deprecated
```
